// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDmL9KBDHp-n10HVB2_RzVHOAcP4Dd0p8',
    appId: '1:1035707032072:web:c5116191e76142dedb27bd',
    messagingSenderId: '1035707032072',
    projectId: 'reservate-e03c7',
    authDomain: 'reservate-e03c7.firebaseapp.com',
    storageBucket: 'reservate-e03c7.firebasestorage.app',
    measurementId: 'G-LY4CR3WN53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBROQQyhFoTzhMNQhYNc0dQNTeh-DiPioE',
    appId: '1:1035707032072:android:287f0cbec7c7b0b6db27bd',
    messagingSenderId: '1035707032072',
    projectId: 'reservate-e03c7',
    storageBucket: 'reservate-e03c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc3VoH2wOBKNAo_W2_uEEWERrpWVqEDNc',
    appId: '1:1035707032072:ios:a46115564e1871f9db27bd',
    messagingSenderId: '1035707032072',
    projectId: 'reservate-e03c7',
    storageBucket: 'reservate-e03c7.firebasestorage.app',
    iosBundleId: 'com.example.reservate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc3VoH2wOBKNAo_W2_uEEWERrpWVqEDNc',
    appId: '1:1035707032072:ios:a46115564e1871f9db27bd',
    messagingSenderId: '1035707032072',
    projectId: 'reservate-e03c7',
    storageBucket: 'reservate-e03c7.firebasestorage.app',
    iosBundleId: 'com.example.reservate',
  );
}
